apiVersion: v1
kind: ConfigMap
metadata:
  namespace: openshift-cluster-csi-drivers
  name: vsphere-csi-config
data:
  cloud.conf: |
    [Global]
    cluster-id = "${CLUSTER_ID}"
    [VirtualCenter "${VCENTER}"]
    insecure-flag = "true"
    datacenters = "${DATACENTERS}"
    [Labels]
    region = k8s-region
    zone = k8s-zone
